name: fittin_admin_panel
description: "Flutter project for Fittin"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.1
  yandex_geocoder: 2.3.1
  get_it: ^7.2.0
  auto_route: ^8.1.3
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  file_picker: ^8.0.5
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:


  uses-material-design: true

  assets:
    - assets/images/